
import { Artwork, UserProfile } from './types';

export const mockArtworks: Artwork[] = [
  {
    id: '1',
    title: 'Ethereal Forest',
    artist: 'PixelMaster',
    price: 25.99,
    description: 'A mystical forest scene with ethereal lighting and magical creatures hidden among the trees.',
    imageUrl: '/placeholder.svg',
    dimensions: '64x64px',
    category: 'Landscape',
    tags: ['forest', 'magic', 'nature'],
    createdAt: new Date(2023, 1, 15).toISOString(),
  },
  {
    id: '2',
    title: 'Cyberpunk City',
    artist: 'NeonArtist',
    price: 34.99,
    description: 'A futuristic cyberpunk cityscape with neon lights and towering skyscrapers.',
    imageUrl: '/placeholder.svg',
    dimensions: '128x64px',
    category: 'Urban',
    tags: ['cyberpunk', 'city', 'futuristic'],
    createdAt: new Date(2023, 2, 10).toISOString(),
  },
  {
    id: '3',
    title: 'Desert Oasis',
    artist: 'SandSculptor',
    price: 19.99,
    description: 'A peaceful oasis in the middle of a vast desert, with palm trees and a crystal clear pool.',
    imageUrl: '/placeholder.svg',
    dimensions: '64x64px',
    category: 'Landscape',
    tags: ['desert', 'oasis', 'peaceful'],
    createdAt: new Date(2023, 3, 5).toISOString(),
  },
  {
    id: '4',
    title: 'Space Explorer',
    artist: 'CosmicPixels',
    price: 29.99,
    description: 'A lone astronaut exploring an alien planet with strange flora and rock formations.',
    imageUrl: '/placeholder.svg',
    dimensions: '96x96px',
    category: 'Sci-Fi',
    tags: ['space', 'astronaut', 'exploration'],
    createdAt: new Date(2023, 4, 20).toISOString(),
  },
  {
    id: '5',
    title: 'Underwater Kingdom',
    artist: 'OceanBits',
    price: 22.99,
    description: 'A vibrant underwater scene featuring a hidden mermaid kingdom with coral castles.',
    imageUrl: '/placeholder.svg',
    dimensions: '128x64px',
    category: 'Fantasy',
    tags: ['underwater', 'mermaid', 'ocean'],
    createdAt: new Date(2023, 5, 12).toISOString(),
  },
  {
    id: '6',
    title: 'Medieval Village',
    artist: 'HistoryBits',
    price: 27.99,
    description: 'A bustling medieval village with marketplaces, blacksmiths, and a towering castle.',
    imageUrl: '/placeholder.svg',
    dimensions: '128x128px',
    category: 'Historical',
    tags: ['medieval', 'village', 'castle'],
    createdAt: new Date(2023, 6, 8).toISOString(),
  },
];

export const mockUserProfile: UserProfile = {
  id: 'user1',
  username: 'ArtEnthusiast',
  avatar: '/placeholder.svg',
  email: 'user@example.com',
  wishlist: [],
  purchases: [],
};
